name: Learning GitHub Script

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Comment on new issue
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const issueBody = fs.readFileSync(".github/ISSUE_RESPONSES/comment.md", "utf8")
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueBody
            })
      - name: Add issue to project board
        uses: actions/github-script@0.8.0
        if: contains(github.event.issue.labels.*.name, 'bug')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |                   
            github.projects.createCard({
            column_id: 17258180,
            content_id: context.payload.issue.id,
            content_type: "Issue"
            });
